name: laboratorio-engenharia

services:
  app_moedas:
    build:
      context: ./ingestao_moedas
      dockerfile: Dockerfile
    container_name: app_coleta_cripto
    depends_on:
      postgres_db:
        condition: service_started
    env_file:
      - ./ingestao_moedas/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres_db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    restart: always
    networks:
      - rede_dados

  postgres_db:
    image: postgres:15
    container_name: pg_engenharia
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./meus_dados_locais:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - rede_dados

networks:
  rede_dados:
    driver: bridge